image: docker:19.03.0

stages:
- build
- deploy

#build-docker:
#  tags: 
#   - docker-runner
#  services:
#  - docker:dind
#
#  before_script:
#  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
#  
#  stage: build
#  script:
#  - docker build -t sendmessages . 
#  - docker tag sendmessages $CI_REGISTRY_USER/sendmessages:latest
#  - docker push mvinnicius1312/sendmessages:latest

deploy-app:
  stage: deploy
  tags:
    - ezops
  script:
    #- 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$STAGING_PRIVATE_KEY" |  tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    #- '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    #- ssh -p22 ubuntu@175.31.15.183 "pwd"
    #- ssh ubuntu@175.31.15.183 "pwd"
    - ssh ubuntu@15.228.185.173 "pwd"

  only:
    - master