image: docker:stable

stages:
- build
- deploy

build-docker:
  tags: 
   - runner-dind
  services:
   - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

  before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  
  stage: build
  script:
  - docker build -t sendmessages . 
  - docker tag sendmessages $CI_REGISTRY_USER/sendmessages:latest
  - docker push $CI_REGISTRY_USER/sendmessages:latest

deploy-app:
  stage: deploy
  tags:
    - runner-dind
  before_script:
    #- 'command -v ssh-agent >/dev/null || ( apt update -y && apt install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$STAGING_PRIVATE_KEY" |  tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - ssh -p22 ubuntu@18.231.184.13
    - echo "OK!"
  only:
    - master