image: docker:19.03.0

stages:
- build
- deploy

build-docker:
  services:
  - docker:dind

  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

  before_script:
  - docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY_PASSWORD

  script:
  - docker build -t sendmessages . 
  - docker tag sendmessages mvinnicius1312/sendmessages:latest
  - docker push mvinnicius1312/sendmessages:latest

  stage: build
  tags: 
    - docker-runner
  script:
  - docker images