image: docker:latest

stages:
- build
- deploy

build-docker:
  services:
  - docker:latest

  before_script:
  - docker build -t sendmessages . 

  stage: build
  tags: 
    - docker-runner
  script:
  - echo "Teste"