image: docker:19.03.0

stages:
- build
- deploy

build-docker:
  tags: 
   - docker-runner
  services:
  - docker:dind

  before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  
  stage: build
  script:
  - docker build -t sendmessages . 
  - docker tag sendmessages $CI_REGISTRY_USER/sendmessages:latest
  - docker push mvinnicius1312/sendmessages:latest

deploy-app:
  stage: deploy
  script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$STAGING_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh -p22 ec2-user@$PROD_DEPLOY_IP "ls -la"
  only:
    - master