image: docker:19.03.0

stages:
- build
- deploy

build-docker:
  services:
  - docker:dind

  before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

  script:
  - docker build -t sendmessages . 

  stage: build
  tags: 
    - docker-runner
  script:
  - echo "Teste"