image: docker:19.03.0

stages:
- build
- deploy

build-docker:
  services:
  - docker:dind

  before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  
  stage: build
  script:
  - docker build -t sendmessages . 
  - docker tag sendmessages $CI_REGISTRY_USER/sendmessages:latest
  - docker push mvinnicius1312/sendmessages:latest

  
